import { createTheme, type CSSVariablesResolver } from "@mantine/core";

export const taskdroidTheme = createTheme({
  primaryColor: "taskdroid",
  primaryShade: { light: 6, dark: 7 },
  colors: {
    taskdroid: [
      "#edf3ff",
      "#dce8ff",
      "#bed3ff",
      "#92b4fb",
      "#6491ec",
      "#4777df",
      "#2f64d6",
      "#2452bb",
      "#1c4398",
      "#173978",
    ],
    dark: [
      "#f6f4fb",
      "#d8d2e8",
      "#c9c1db",
      "#b4aacc",
      "#9f95be",
      "#8b80ad",
      "#766b9a",
      "#635985",
      "#443c68",
      "#18122b",
    ],
  },
  fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
  fontFamilyMonospace: "ui-monospace, SFMono-Regular, Menlo, monospace",
  headings: {
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
    fontWeight: "700",
  },
  defaultRadius: "md",
  radius: { xs: "4px", sm: "6px", md: "8px", lg: "10px", xl: "12px" },
  spacing: { xs: "6px", sm: "8px", md: "12px", lg: "16px", xl: "24px" },
  shadows: {
    xs: "0 1px 2px rgb(27 41 69 / 10%)",
    sm: "0 4px 16px rgb(23 32 51 / 16%)",
  },
  other: {
    colors: {
      success: "#31a66a",
      warning: "#ca8a04",
      danger: "#c5393e",
    },
  },
});

export const taskdroidCssVariablesResolver: CSSVariablesResolver = () => ({
  variables: {
    "--taskdroid-radius-card": "var(--mantine-radius-lg)",
    "--taskdroid-shadow-card": "var(--mantine-shadow-xs)",
    "--taskdroid-focus-ring": "var(--mantine-color-taskdroid-6)",
  },
  light: {
    "--taskdroid-app-background": "#f4f6f9",
    "--taskdroid-surface": "#ffffff",
    "--taskdroid-surface-raised": "#ffffff",
    "--taskdroid-surface-muted": "#e9edf3",
    "--taskdroid-surface-inset": "#f4f6f9",
    "--taskdroid-surface-hover": "#f4f7fd",
    "--taskdroid-text": "#172033",
    "--taskdroid-text-muted": "#687287",
    "--taskdroid-text-subtle": "#7a8497",
    "--taskdroid-border": "#dfe3ea",
    "--taskdroid-border-subtle": "#e6e9ef",
    "--taskdroid-progress-track": "#dfe4ec",
    "--taskdroid-success": "#31a66a",
    "--taskdroid-link": "#2f64d6",
    "--taskdroid-selected-surface": "#eef3ff",
    "--taskdroid-error-surface": "#ffeaeb",
    "--taskdroid-error-text": "#9f2028",
    "--taskdroid-shadow-card": "0 1px 2px rgb(27 41 69 / 8%)",
    "--taskdroid-shadow-float": "0 6px 28px rgb(23 32 51 / 20%)",
    "--taskdroid-shadow-dialog": "0 20px 60px rgb(0 0 0 / 31%)",
  },
  dark: {
    "--taskdroid-app-background": "#18122b",
    "--taskdroid-surface": "#241d3b",
    "--taskdroid-surface-raised": "#393053",
    "--taskdroid-surface-muted": "#443c68",
    "--taskdroid-surface-inset": "#211a36",
    "--taskdroid-surface-hover": "#635985",
    "--taskdroid-text": "#f6f4fb",
    "--taskdroid-text-muted": "#d8d2e8",
    "--taskdroid-text-subtle": "#c9c1db",
    "--taskdroid-border": "#8b80ad",
    "--taskdroid-border-subtle": "#635985",
    "--taskdroid-progress-track": "#443c68",
    "--taskdroid-success": "#57c785",
    "--taskdroid-link": "#92b4fb",
    "--taskdroid-selected-surface": "#393053",
    "--taskdroid-error-surface": "#4b253e",
    "--taskdroid-error-text": "#ffb7b8",
    "--taskdroid-shadow-card": "0 1px 3px rgb(0 0 0 / 25%)",
    "--taskdroid-shadow-float": "0 8px 26px rgb(0 0 0 / 42%)",
    "--taskdroid-shadow-dialog": "0 20px 60px rgb(0 0 0 / 55%)",
    "--mantine-color-body": "#18122b",
    "--mantine-color-text": "#f6f4fb",
    "--mantine-color-dimmed": "#d8d2e8",
    "--mantine-color-default": "#241d3b",
    "--mantine-color-default-hover": "#393053",
    "--mantine-color-default-color": "#f6f4fb",
    "--mantine-color-default-border": "#8b80ad",
    "--mantine-color-placeholder": "#c9c1db",
  },
});
